language: java

os: 
  - linux
#  - osx

env:
  - VERSION=esr60

cache:
   directories:
      - /tmp/compactheader/ftp/
     
before_install:
  - if echo "$TRAVIS_COMMIT_MESSAGE" | grep -F -q "[skip travis]" ; then echo "[skip travis] has been found, exiting" && exit 0 ; else echo "[skip travis] has not been found, continuing" ; fi
  - |
    if [[ $TRAVIS_OS_NAME != 'osx' ]]; then
      sudo apt-get install metacity
    else
      HOMEBREW_NO_AUTO_UPDATE=1 brew install ant
    fi

before_script:
  - wget https://downloads.sourceforge.net/project/xmltask/xmltask/1.16.1/xmltask.jar 
  - export CLASSPATH=`pwd`/xmltask.jar:$CLASSPATH
  - |
    if [[ $TRAVIS_OS_NAME != 'osx' ]]; then
      export DISPLAY=:99.0
      /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1920x1080x16  -extension RANDR
      sleep 5 # give xvfb some time to start
      metacity --sm-disable --replace 2>/dev/null &
      sudo python2 -m pip install --upgrade pyOpenSSL
      sudo python2 -m pip install --upgrade urllib3[secure]
      sudo python2 -m pip install bs4
      sudo python2 -m pip install lxml
      sudo python2 -m pip install requests
      sudo python2 -m pip install treeherder-client
    fi
  - |
    if [[ $TRAVIS_OS_NAME == 'osx' ]]; then
      /Library/Application\ Support/VMware\ Tools/vmware-resolutionSet 1400 1200 #  1280 x 1024
      system_profiler SPDisplaysDataType | grep Resolution
      wget -qO- https://bootstrap.pypa.io/get-pip.py | sudo python2
      sudo python2 -m pip install urllib3[secure]
      sudo python2 -m pip install bs4
      sudo python2 -m pip install lxml
      sudo python2 -m pip install requests
      sudo python2 -m pip install treeherder-client
      export PIP_INDEX_URL=http://pypi.pub.build.mozilla.org/pub
      export PIP_TRUSTED_HOST="pypi.pub.build.mozilla.org"
      export PIP_FIND_LINKS="/tmp/compactheader http://pypi.pub.build.mozilla.org/pub"
    fi

script: 
  - ant buildAMO
  - cd test
  - python2 ./find_nightly_build.py --version $VERSION
  - python2 ./executeTests.py --version $VERSION
