language: java

os: 
  - osx
  - linux

env:
  - VERSION=ESR
  - VERSION=nightly

before_install:
  - if echo "$TRAVIS_COMMIT_MESSAGE" | grep -F -q "[skip travis]" ; then echo "[skip travis] has been found, exiting" && exit 0 ; else echo "[skip travis] has not been found, continuing" ; fi
  - |
    if [[ $TRAVIS_OS_NAME != 'osx' ]]; then
      sudo apt-get install metacity
    else
      HOMEBREW_NO_AUTO_UPDATE=1 brew install ant
      python --version
      python -c "import ssl; print(ssl.OPENSSL_VERSION)"
    fi

before_script:
  - wget https://downloads.sourceforge.net/project/xmltask/xmltask/1.16.1/xmltask.jar 
  - export CLASSPATH=`pwd`/xmltask.jar:$CLASSPATH
  - |
    if [[ $TRAVIS_OS_NAME != 'osx' ]]; then
      export DISPLAY=:99.0
      /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1920x1080x16  -extension RANDR
      sleep 5 # give xvfb some time to start
      metacity --sm-disable --replace 2>/dev/null &
    fi

script: 
  - ant buildAMO
  - cd test
  - python ./executeTests.py --version $VERSION
